image:
  file: .gitpod.Dockerfile
  
ports:
  - port: 3007
    onOpen: open-browser
    visibility: public
  - port: 4000
    onOpen: open-browser
    visibility: public
  - port: 3006
    onOpen: ignore
    visibility: public
  - port: 8080
    onOpen: ignore
    visibility: public

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - graphql.vscode-graphql
    - yzhang.markdown-all-in-one
    - ms-vscode.vscode-typescript-tslint-plugin
    - hediet.vscode-drawio
    - ms-azuretools.vscode-docker

tasks:
  - init: npm run gitpod-init;  docker pull deepf/deeplinks:main; npm install -g concurrently; npx concurrently --kill-others "npm run gitpod-start" "sleep 90; npm run gitpod-migrate";
  - command: npm run gitpod-start;
  
