image:
  file: .gitpod.Dockerfile

ports:
  - port: 3007
    onOpen: open-browser
    visibility: public
  - port: 3006
    onOpen: ignore
    visibility: public
  - port: 8080
    onOpen: ignore
    visibility: public

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - graphql.vscode-graphql
    - yzhang.markdown-all-in-one
    - ms-vscode.vscode-typescript-tslint-plugin
    - hediet.vscode-drawio
    - ms-azuretools.vscode-docker

tasks:
  - init: npm run gitpod-prepare; gp open readme.md; npm ci; npm run packages; npm run git-shh-to-https; npm run gitpod-init; docker volume create deep_db_data && docker run -v deep_db_data:/data --rm --name links --entrypoint "sh" deepf/deeplinks:main -c "cd / && tar xvf /backup/volume.tar --strip 1"; wget -O /workspace/dev/packages/deeplinks/.migrate https://gist.githubusercontent.com/Konard/ec2043da66bc7a1e970156189b4ff5e7/raw/dbcc4adc02a336bc23b5274e06485c13a29acfd1/.migrate;
  - command: npm run gitpod-start;
  
