image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
    npm install && (
      (yes | sudo apt install screen) && screen -d -m sudo docker-up
    ) && (
      npx gulp packages:get
    ) && (
      npx gulp packages:links
    ) && (
      cd packages/store-example && npm run dev -- -p 3000
    ) && (
      cd packages/hasura-example && npm run dev -- -p 3001
    ) && (
      cd packages/hasura && AUTH_WEBHOOK=http://dockerhost:3001/api/auth/webhook npm run docker-local
    )

vscode:
  extensions:
    - ms-azuretools.vscode-docker@1.9.1:QdS6HgHvji4YGIWRWKXrLA==
    - graphql.vscode-graphql@0.3.8:jHk/gSNypa0bHc+cU2gp8w==
    - yzhang.markdown-all-in-one@3.4.0:GR9Y7wA3m2/LsuZxLaCFtg==
    - ms-vscode.vscode-typescript-tslint-plugin@1.2.2:0nQ3PEEA0NPEt3UcbCYiIQ==